empty-commit

diff --git a/bin/build_smartos b/bin/build_smartos
--- a/bin/build_smartos
+++ b/bin/build_smartos
@@ -21,21 +21,21 @@ usage() {
 
 	Options:
 
-	       None at this time.
+			None at this time.
 
 	Arguments:
-    
-	       BUILD_BASE      Build image to use for base of the image.  This image
-	                       must already exist in the ZFS hierarchy.
-	                       e.g. base64-13.2.1
 
-	       BUILD_ZONE      Build zone to use for building out the image.  The
-	                       UUID of a zone that is already installed and running.
-	                       e.g. b23882cc-3d9e-11e3-aa2f-83b8d8746936
+		BUILD_BASE	Build image to use for base of the image.  This image
+					must already exist in the ZFS hierarchy.
+					e.g. base64-13.2.1
 
-	       BUILD_REPO      Build repository to use which contains the necessary
-	                       build files for the image.
-	                       e.g. mi-percona
+		BUILD_ZONE	Build zone to use for building out the image.  The
+					UUID of a zone that is already installed and running.
+					e.g. b23882cc-3d9e-11e3-aa2f-83b8d8746936
+
+		BUILD_REPO	Build repository to use which contains the necessary
+					build files for the image.
+					e.g. mi-percona
 
 	EOF
 
@@ -45,16 +45,18 @@ mi_version="1.0.0";
 
 shift $(($OPTIND - 1))
 if [[ $# = 3 ]]; then
-        mi_bimage="$1";
-        mi_bzone="$2";
-        mi_brepo="$3";
+	mi_bimage="$1";
+	mi_bzone="$2";
+	mi_brepo="$3";
 else
-        usage;
+	usage;
 fi
 
 # Set mi_home and source mi_home/lib/mibe.inc if exists
 mi_home=$(dirname $(cd ${0%/*} && pwd -P));
-[[ -s "${mi_home}/lib/mibe.inc" ]] && source ${mi_home}/lib/mibe.inc || { echo "* ERROR - ${mi_home}/lib/mibe.inc not found, can't continue."; exit 1; }
+[[ -s "${mi_home}/lib/mibe.inc" ]] \
+	&& source ${mi_home}/lib/mibe.inc \
+	|| { echo "* ERROR - ${mi_home}/lib/mibe.inc not found, can't continue."; exit 1; }
 
 trap zone_cleanup_sighandler INT TERM;
 
diff --git a/bin/repo_init b/bin/repo_init
--- a/bin/repo_init
+++ b/bin/repo_init
@@ -16,16 +16,16 @@ usage() {
 	Usage: $0 [options] TYPE REPOSITORY
 
 	Arguments:
-    
-        TYPE              Type of build repository to initialize.
-                          Supported types: smartos
-        REPOSITORY        Name of build repository to initialize.
-       	                  eg: mi-percona
+
+		TYPE		Type of build repository to initialize.
+					Supported types: smartos
+		REPOSITORY	Name of build repository to initialize.
+					eg: mi-percona
 
 	Options:
-   
-        -g                Git support.  Assumes your repository is already created
-                          on the server and creates/commits the intial files.
+
+		-g		Git support.  Assumes your repository is already created
+				on the server and creates/commits the intial files.
 
 	EOF
 
@@ -33,26 +33,27 @@ usage() {
 }
 
 while getopts "g" OPTION; do
-        case $OPTION in
-                g)	opt_g="true";	;;
-                *)	usage;		;;
-        esac
+	case $OPTION in
+			g)	opt_g="true";	;;
+			*)	usage;		;;
+	esac
 done
 
 shift $(($OPTIND - 1))
 if [[ $# = 2 ]]; then
-        mi_type="$1";
-        mi_repo="$2";
+	mi_type="$1";
+	mi_repo="$2";
 else
-        usage;
+	usage;
 fi
 
 [[ ${mi_type} != "smartos" ]] && usage;
 
 # Set mi_home and source mi_home/lib/mibe.inc if exists
 mi_home=$(dirname $(cd ${0%/*} && pwd -P));
-[[ -s "${mi_home}/lib/mibe.inc" ]] && source ${mi_home}/lib/mibe.inc || { echo "* ERROR - ${mi_home}/lib/mibe.inc not found,
- can't continue."; exit 1; }
+[[ -s "${mi_home}/lib/mibe.inc" ]] \
+	&& source ${mi_home}/lib/mibe.inc \
+	|| { echo "* ERROR - ${mi_home}/lib/mibe.inc not found, can't continue."; exit 1; }
 
 mi_image=$(echo ${mi_repo} | sed 's/mi-//g');
 get_reposdir;
